apiVersion: v1
kind: Namespace
metadata:
  name: nnnn-staging
  labels:
    environment-id: env_91436a6d-7c29-45c0-9e00-4a570edfc14d
    project-id: project_1b4f830c-2534-4368-9e90-a86c83e4822d
    project-name: nnnn
    environment-name: staging
    organization-id: org_7a7c68a9-0d1d-4ef5-ad4d-40b555ceddd1
